### ISSUE TITLE
Upgrade to pyroma 4.1?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/code-quality#14]
Since today `pyroma` 4.1 is available, which needs extra dependency `trove-classifiers==2022.10.19`. I have updated these versions in the coredev buildout.
Problem: this will give errors for a lot of Plone packages, because most of them do not have the `requires_python` metadata, which it now complains about. For example in `plone.schemaeditor`:

```
$ ../../bin/pyroma .
------------------------------
Checking .
Getting metadata for wheel...
Found plone.schemaeditor
------------------------------
You should specify what Python versions you support with the 'requires-python'/'python_requires' metadata.
------------------------------
Final rating: 8/10
Philadelphia
------------------------------
```

Not many Plone packages use this tool yet, so maybe it is fine to upgrade.

Sample line in `setup.py` for Plone 6.0:

    python_requires=">=3.8"

Sample for Plone 5.2 only:

    python_requires=">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,<3.9"

**Comment by fredvd** [comment]
pyroma 4.2 was added in code-quality 2.1.1 . Closing this issue
