### ISSUE TITLE
README outdated?

### ISSUE THREAD

**Issue by gforcada** [plone/code-quality#15]
Hi, I'm trying to figure out how to use this docker image to generally enable linting/formatting GHA workflows on all plone packages, and as pointed by @mauritsvanrees [plone.dexterity](https://github.com/plone/plone.dexterity/blob/master/.github/workflows/code-analysis.yml) is already using this docker image via the [plone/code-analysis-action](https://github.com/plone/code-analysis-action) 🎉 

Anyway, question is, if I have a local clone of, say, `plone.app.content`, and I'm on the root of that git repository check out and I run (as mentioned on the `README`):

```
docker run --rm -v "${PWD}":/github/workspace plone/code-quality:latest check black
```

Rather than having the code formatted with `black`, I instead get:

```
============================
Starting plone-code-analysis
============================
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 43, in <module>
    settings = read_settings_from_file(settings_file)
  File "/usr/local/lib/python3.10/site-packages/plone_code_analysis/settings.py", line 31, in read_settings_from_file
    if not path.exists():
  File "/usr/local/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/github/workspace/pyproject.toml'
```

Do I miss any step? 🤔 seems to run fine on GHA but not locally...

**Comment by davisagli** [comment]
@gforcada You have to tell docker to run the image with a user that has permission on the files that were mounted from the host filesystem. 

Take a look at the Makefile in plone.dexterity for commands that run the image locally: https://github.com/plone/plone.dexterity/blob/master/Makefile (although, it looks like it is only setting the user when formatting and not when checking, and it seems you might need it for both)
