### ISSUE TITLE
How do I run a fix command (e.g. for zpretty?)

### ISSUE THREAD

**Issue by tisto** [plone/code-quality#4]
Most tools that are used in this repo have a check and a fix option.

You can run the check/lint option for zpretty with:

```
docker run --rm -v "${PWD}":/github/workspace plone/code-quality:latest check zpretty src
```

How are we supposed to run the fix command? Can the docker container access and change the fs? 

```
docker run --rm -v "${PWD}":/github/workspace plone/code-quality:latest check zpretty --inplace src
```

does not work.

If I'd install zpretty locally and run it, I would risk to use a different version locally that would do a different formatting than the one I have on CI.

**Comment by ericof** [comment]
Implemented on #9
