### ISSUE TITLE
Allow to run all linters

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/code-quality#6]
Currently, you need to run all linters individually:

```
check isort <paths>
check black <paths>
check pyroma .
etc...
```

It would be nice if you can call `check` and have all checkers run. This would make the Makefiles and gh-actions configs smaller.
A prerequisite for this seems that we should read configuration from a file, see issue #5.

Bonus points if all checks are run, also when a previous check has already failed.
But the exit code must be 1 to indicate an error if any of the checks fails.

**Comment by ericof** [comment]
Implemented on #9
